"use server";

import { revalidatePath } from "next/cache";

import { currentUser } from "@/lib/auth";
import { batch, one, run } from "@/lib/db";

export interface LibraryResult {
  ok?: true;
  error?: string;
}

/**
 * Ids are generated by `uid()` — a prefix, an underscore and twenty hex
 * characters. Anything else did not come from us, and is refused before it
 * reaches a query rather than being escaped on the way in.
 */
const ID = /^[A-Za-z][A-Za-z0-9]*_[a-f0-9]{1,64}$/;

/** The owning row, or null when it is not this person's to touch. */
async function ownedBy(id: string, userId: string) {
  const row = await one(
    `SELECT id, kind, title FROM conversations WHERE id = ? AND user_id = ?`,
    [id, userId],
  );
  return row ?? null;
}

/**
 * Removes a saved document, deck, sheet or thread for good.
 *
 * The messages are deleted explicitly rather than left to ON DELETE CASCADE.
 * SQLite enforces foreign keys only when `PRAGMA foreign_keys = ON`, which
 * this database never sets, so the cascade in the schema does nothing — a
 * conversation deleted on its own would leave its messages behind forever,
 * invisible and still taking up space.
 *
 * The paired Recents row is matched with `instr` rather than LIKE: the id is
 * user-supplied, and in a LIKE pattern a `%` in it would match rows belonging
 * to other saved work. `instr` has no pattern syntax to abuse.
 */
export async function deleteSaved(id: string): Promise<LibraryResult> {
  const user = await currentUser();
  if (!user) return { error: "Log in to manage your saved work." };
  if (!ID.test(id)) return { error: "That is not a valid item." };

  const owned = await ownedBy(id, user.id);
  // Deliberately the same message as a genuinely missing row: telling someone
  // that an id exists but belongs to somebody else is itself a disclosure.
  if (!owned) return { error: "That item no longer exists." };

  await batch([
    { sql: `DELETE FROM messages WHERE conversation_id = ?`, args: [id] },
    {
      sql: `DELETE FROM conversations WHERE id = ? AND user_id = ?`,
      args: [id, user.id],
    },
    {
      sql: `DELETE FROM recents WHERE user_id = ? AND instr(href, ?) > 0`,
      args: [user.id, id],
    },
  ]);

  revalidatePath("/", "layout");
  return { ok: true };
}

const MAX_TITLE = 90;

/** Renames a saved item, keeping the Recents strip in step with it. */
export async function renameSaved(
  id: string,
  title: string,
): Promise<LibraryResult> {
  const user = await currentUser();
  if (!user) return { error: "Log in to manage your saved work." };
  if (!ID.test(id)) return { error: "That is not a valid item." };

  const clean = title.replace(/\s+/g, " ").trim().slice(0, MAX_TITLE);
  if (clean.length < 1) return { error: "Give it a name." };

  const owned = await ownedBy(id, user.id);
  if (!owned) return { error: "That item no longer exists." };

  await batch([
    {
      sql: `UPDATE conversations SET title = ? WHERE id = ? AND user_id = ?`,
      args: [clean, id, user.id],
    },
    {
      sql: `UPDATE recents SET title = ? WHERE user_id = ? AND instr(href, ?) > 0`,
      args: [clean, user.id, id],
    },
  ]);

  revalidatePath("/", "layout");
  return { ok: true };
}

/**
 * Empties one kind — every saved document, or every saved deck.
 *
 * Separate from deleting them one at a time because the strip keeps twelve
 * per kind and clearing it row by row is twelve confirmations.
 */
export async function clearKind(kind: string): Promise<LibraryResult> {
  const user = await currentUser();
  if (!user) return { error: "Log in to manage your saved work." };
  if (!/^[a-z]{1,16}$/.test(kind)) return { error: "Unknown kind." };

  // Message rows are reached through their conversation, and again the
  // cascade cannot be relied on to do it.
  await run(
    `DELETE FROM messages WHERE conversation_id IN (
       SELECT id FROM conversations WHERE user_id = ? AND kind = ?
     )`,
    [user.id, kind],
  );
  await batch([
    {
      sql: `DELETE FROM conversations WHERE user_id = ? AND kind = ?`,
      args: [user.id, kind],
    },
    { sql: `DELETE FROM recents WHERE user_id = ? AND kind = ?`, args: [user.id, kind] },
  ]);

  revalidatePath("/", "layout");
  return { ok: true };
}
